# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: akhileshns/heroku-deploy@v3.8.9
      uses: actions/setup-python@v2
      with:
          heroku_api_key: ${{secrets.HEROKU}}
          heroku_app_name: "integracion"
          heroku_email: "tojandro@gmail.com"
          procfile: "web: npm start"
    - name: Requerimientos
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Prueba python3
      run: python3 manage.py test
